theme: jekyll-theme-hacker
title: [Machine Learning]
description: [Machine Learning o'zbek tilida]
show_downloads: false
show_github_repository: false
show_description: true
show_visitors: true
is_theme_by: false

github:
  martianvenusianorg_url: https://martianvenusianorg.github.io 
  home_url: https://martianvenusianorg.github.io/machine_learning
  repository_name: [Machine Learning]
